import type { Metadata } from "next";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Projects",
  description: "Generated by create next app",
};

export default async function ProjectsLayout({
  children,
}: {
  children: ReactNode;
}) {
  return <>{children} </>;
}
