import "@/styles/globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Contact",
    description: "Generated by create next app",
};

export default async function ContactLayout({ children }: { children: React.ReactNode }) {
    return (
        <main className="container flex gap-4 flex-wrap md:flex-nowrap justify-center items-baseline py-24">
            {children}
        </main>
    );
}
