import type { Metadata } from "next";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Contact",
  description: "Generated by create next app",
};

export default async function ContactLayout({
  children,
}: {
  children: ReactNode;
}) {
  return <>{children} </>;
}
